title: Statistics
description: >-
  Personal blog for the Statistics course in Cybersecurity
url: "https://statistics.jcondor.me"
lang: en
github_username: jcondor98
repository: jcondor98/statistics

plugins:
  - jekyll-feed

theme: jekyll-theme-cayman
