title: Statistics
# email: example@example.org
description: >-
  Personal blog for the Statistics course in Cybersecurity
url: "https://statistics.jcondor.me"
lang: en
github_username: jcondor98

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

hide_share_buttons: true

paginate: 5
paginate_path: "/blog/page:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
